<!DOCTYPE html>
<html lang="ar">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>الواجهة الوسيطة</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            text-align: center;
        }
        .container {
            max-width: 800px;
            margin: 50px auto;
            background: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            padding: 10px;
            border: 1px solid #ddd;
        }
        th {
            background: #007bff;
            color: #fff;
        }
        button {
            padding: 10px 20px;
            background: #28a745;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }
        button:hover {
            background: #218838;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>الواجهة الوسيطة</h1>
        <p>إدارة الطلبات بين العميل والمالك</p>

        <table>
            <thead>
                <tr>
                    <th>رقم الطلب</th>
                    <th>الاسم</th>
                    <th>الخدمة</th>
                    <th>التاريخ</th>
                    <th>الوقت</th>
                    <th>الحالة</th>
                </tr>
            </thead>
            <tbody id="requests">
                <!-- سيتم تعبئة الطلبات هنا ديناميكياً -->
            </tbody>
        </table>

        <button onclick="syncData()">تحديث البيانات</button>
    </div>

    <script>
        // جلب البيانات من قاعدة البيانات وعرضها
        function syncData() {
            fetch('http://localhost:3000/api/bookings')
                .then(response => response.json())
                .then(bookings => {
                    const requestsTable = document.getElementById('requests');
                    requestsTable.innerHTML = ''; // تنظيف الجدول

                    bookings.forEach(booking => {
                        const row = document.createElement('tr');
                        row.innerHTML = `
                            <td>${booking.id}</td>
                            <td>${booking.name}</td>
                            <td>${booking.service}</td>
                            <td>${booking.date}</td>
                            <td>${booking.time}</td>
                            <td>${booking.status}</td>
                        `;
                        requestsTable.appendChild(row);
                    });
                })
                .catch(err => console.error(err));
        }

        // التحديث عند تحميل الصفحة
        window.onload = syncData;
    </script>
</body>
</html>
